export const SET_CHARACTER = 'SET_CHARACTER'

export const SET_PALYING_STATE = 'SET_PALYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PALY_MODE = 'SET_PALY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'